name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: OpenMP make
      run: cd code_samples/sample_01 && make
    - name: OpenMP make run with 2 threads
      run: cd code_samples/sample_01 && make run THREADS=2
